#!/bin/bash

interval=1

while true; do

    full_status=$(acpi | cut -d ":" -f2 | cut -d"," -f1 | tr -d " ")
    percent=$(acpi | cut -d ":" -f2 | cut -d"," -f2 | tr -d " " | tr -d "%")
    
    if [ "$full_status" == "Charging" ]; then
	stat="CHR"
	if [ $percent -eq 100 ]; then
	    color="#00FF00"
	else
	    color="#AAAAAA"
	fi
	    
    elif [ "$full_status" == "Discharging" ]; then
	stat="DIS"
	if [ $percent -le 5 ]; then
	    systemctl suspend
	elif [ $percent -le 20 ]; then
	    color="#FF0000"
	elif [ $percent -le 40 ]; then
	    color="#FFAE00"
	elif [ $percent -le 60 ]; then
	    color="#FFF600"
	elif [ $percent -lt 85 ]; then
	    color="#A8FF00"
	else
	    color="#00FF00"
	fi
    else
	stat=""
	if [ $percent -eq 100 ]; then
	    color="#00FF00"
	else
	    color="#AAAAAA"
	fi
    fi

    full_text="<span foreground='$(echo $color)'>$(echo $percent\% $stat)</span>"

    echo $full_text

    sleep $interval
done
