#!/bin/bash

# Core number is defined by the block instance
coreno=$BLOCK_INSTANCE

# define high and critical values
high=80
crit=105

temp=$(sensors | grep "Core $(echo $coreno)" | cut -d'+' -f2 | cut -d' ' -f1)

# fulltext and shorttext are the same
echo +$temp
echo +$temp

# compare temerature to high and critical values to produce color output
tempno=$(echo $temp | cut -d'.' -f1)

if [ $tempno -lt $high ] ; then
    echo "#AAAAAA"
elif [ $tempno -lt $crit ] ; then
    echo "#FFFF00"
else
    echo "#FF0000"
fi

