#!/bin/bash

#weather report using wttr.in

wtr=$(curl wttr.in/\?format=%c%20%t%20%20%20%h)

if [[ $wtr == *"Unknown"* ]]; then
    wtr="?"
fi

echo $wtr

case $BLOCK_BUTTON in
    1) urxvt -e w3m wttr.in ;;
esac
