* MY CONFIG FILES

** OVERVIEW
UNDER (constant) CONSTRUCTION

Dakode's configuration files (also some scripts). Keeping them all in one place, then use hardlinks to copy them to the correct path (see [[FILES AND LOCATIONS]] section).

Configured programs:
- i3 (window manager)
- ranger (file manager)
- zsh (shell)
- urxvt (terminal emulator -- uses Xresources file)
- dunst (notifications)
- compton (compositor -- transparency and stuff)

Some usefull scripts that come and go, rising briefly into glory and then falling to obscurity...

- Important note: The logic behind this approach is that editing the hard link will edit the file itself. However this will not work if your editor keeps some kind of backup file that overwrites the original file, because it changes its inode number. For example, in emacs, I had to specify to keep backup files by copying the original file.

** FILES AND LOCATIONS
- "compton.conf" "$HOME/.config/compton.conf"
- "i3/config" "$HOME/.i3/config"
- "i3/i3blocks.conf" "$HOME/.i3/i3blocks.conf"
- "i3/i3blocks/*" "$HOME/.i3/i3blocks/*"
- "ranger/*" "$HOME/.config/ranger/*"
- "scripts/*" "$HOME/.config/scripts"
- "zshrc" "$HOME/.zshrc"
- "Xresources" "$HOME/.Xresources"

Note that the scripts directory must be added to your path

** SYSTEM, PROGRAMS, DEPENDENCIES
- System: Manjaro Linux with the i3 window manager (some scripts and stuff used are part of the installation and thus not yet included here, for example the shutdown scripts).
- Window manager: i3 (i3-gaps)
- Terminal emulator: urxvt (rxvt-unicode)
- Editor: emacs (run as daemon, using clients)
- File manager: ranger
- Browser: palemoon
- Mail client: thunderbird
- Music player: mocp
- Video player: smplayer
- Net management: NetworkManager
- Torrent manager: transmission-daemon with tremc frontend
- Display settings: xrandr, xbacklight, compton, feh, w3m
- Audio management: pulseaudio, pactl
- Notifications: dunst, conky (with default scripts from Manjaro)
- Status bar: i3blocks
- Mount/unmount: udiskie
- Misc: youtube-dl, xkb-switch
- System fonts: Jura, Abel, FontAwesome, IcoMoon

** TODO-list

*** TODO
Write sync script to add and manage config files.
I started implementig this. The =filelist= file is part of this iplementation.
*** TODO
Link the file =filelist= to this README.
*** TODO
(Maybe) Include a folder with system configs only for reference (eg sudoers, fstab etc)
