
# broot config just to select and spit out file names.
# overrides most default bindings
# for use in scripts or with lf

default_flags = ""

show_selection_mark = true

[[verbs]]
key = "enter"
execution = ":print_path"

[[verbs]]
key = "ctrl-c"
execution = ":quit"

[[verbs]]
key = "ctrl-h"
execution = ":parent"

[[verbs]]
key = "ctrl-l"
execution = ":focus"

[[verbs]]
key = "ctrl-j"
execution = ":line_down"

[[verbs]]
key = "ctrl-k"
execution = ":line_up"

[[verbs]]
key = "ctrl-d"
execution = ":page_down"

[[verbs]]
key = "ctrl-u"
execution = ":page_up"

default = "none none"