
default_flags = ""

show_selection_mark = true

# opening -- default behaviour is to return the path
[[verbs]]
key = "enter"
execution = ":print_path"

[[verbs]]
invocation = "opener"
key = "ctrl-o"
shortcut = "o"
execution = "devour opener {file}"

[[verbs]]
key = "ctrl-c"
execution = ":quit"

# movement
[[verbs]]
key = "ctrl-h"
execution = ":parent"

[[verbs]]
key = "ctrl-l"
execution = ":focus"

[[verbs]]
key = "ctrl-j"
execution = ":line_down"

[[verbs]]
key = "ctrl-k"
execution = ":line_up"

[[verbs]]
key = "ctrl-d"
execution = ":page_down"

[[verbs]]
key = "ctrl-u"
execution = ":page_up"

# skin
default = "none none"