#!/bin/bash

# a new approach --- mine!

# define paths
declare -A path=()

REPO=$HOME/dotfiles

path[config]=$HOME/.config
path[HOME]=$HOME
path[i3]=${path[config]}/i3
path[i3blocks]=${path[i3]}/i3blocks
path[ranger]=${path[config]}/ranger
path[scripts]=${path[config]}/scripts

while getopts ":uld" opt; do
    case $opt in
	u)
	    for dir in "${!path[@]}"; do
		# find command
		find $REPO/$dir -type f | while read -r file; do
		    target=${path[$dir]}/$(basename $file)
		    f_inode=$(ls -i $file | cut -d' ' -f1)
		    t_inode=$(ls -i $target | cut -d' ' -f1)
		    if [[ $f_inode -eq $t_inode ]] ; then
			echo === File $(basename $file) already linked
		    else
			if [ "$file" -nt "$target" ]; then
			    echo Linking file $(basename $file)...
			    ln -f $file $target
			else
			    echo File $(basename $file) is newer in destination. Do a diff or something.
			fi
		    fi
		done
	    done
	    ;;
	l)
	    for dir in "${!path[@]}"; do
		echo $dir '->' ${path[$dir]}:
		find $REPO/$dir -type f | while read -r file; do
		    echo -e "\t$(basename $file)"
		done
	    done
	    exit 0
	    ;;
	d)
	    for dir in "${!path[@]}"; do
		echo $dir '->' ${path[$dir]}
	    done
	    exit 0
	    ;;
	\?)
	    echo "Invalid option: -$OPTARG" >&2
	    exit 1
	    ;;
    esac
done
